name: Ejecutar modelo mascotas

on:
  workflow_dispatch:
    inputs:
      train:
        description: "Â¿Entrenar modelo? (true / false)"
        required: true
        default: "false"

      nuevo:
        description: "Mascotas nuevas (true / false)"
        required: true
        default: "false"
        
      nombre_nuevo:
        description: "Nombre hoja de mascotas nuevas"
        required: true
        default: "false"
    
  schedule:
    - cron: "0 12 * * 4"   # todos los jueves 7:00 AM UTC

jobs:
  run-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear archivo credenciales Google
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: |
          echo "$GOOGLE_CREDS" > service_account.json
          
      - name: Definir variables de entorno
        run: |
          echo "TRAIN=${{ github.event.inputs.train || 'false' }}" >> $GITHUB_ENV
          echo "NUEVO=${{ github.event.inputs.nuevo || 'false' }}" >> $GITHUB_ENV
          echo "NOMBRE_NUEVO=${{ github.event.inputs.nombre_nuevo || 'false' }}" >> $GITHUB_ENV

      - name: Ejecutar modelo
        env:
          GOOGLE_CREDENTIALS_PATH: service_account.json
        run: |
          python modelo-mascotas.py
          
env:
  TRAIN: "false"
